[book]
authors = ["Felicitas Pojtinger", "Jakob Waibel"]
language = "en"
multilingual = false
src = "src"
title = "Uni Software Defined Infrastructure Notes"
description = "Notes for the software defined infrastructure course at HdM Stuttgart."

[build]
build-dir = "out"
